// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of fellows_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class fellows_DetailViewModel : BindableBase, Ifellows_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="fellows_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public fellows_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private fellowsSchema _currentfellowsSchema;

        /// <summary>
        /// CurrentfellowsSchema property.
        /// </summary>		
        public fellowsSchema CurrentfellowsSchema
        {
            get
            {
				return _currentfellowsSchema;
            }
            set
            {
                SetProperty(ref _currentfellowsSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechfellows_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechfellows_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentfellowsSchema.Subtitle + " " + CurrentfellowsSchema.Description);
        }
		

        private ICommand _textToSpeechfellows_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechfellows_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechfellows_DetailStaticControlCommand
        {
            get { return _textToSpeechfellows_DetailStaticControlCommand = _textToSpeechfellows_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechfellows_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharefellows_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharefellows_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentfellowsSchema.Subtitle, CurrentfellowsSchema.Description);
        }
		

        private ICommand _sharefellows_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharefellows_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharefellows_DetailStaticControlCommand
        {
            get { return _sharefellows_DetailStaticControlCommand = _sharefellows_DetailStaticControlCommand ?? new DelegateCommand(Sharefellows_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartfellows_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartfellows_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(Ifellows_DetailViewModel), CreateTileInfofellows_DetailStaticControl());
        }
		

        private ICommand _pinToStartfellows_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartfellows_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartfellows_DetailStaticControlCommand
        {
            get { return _pinToStartfellows_DetailStaticControlCommand = _pinToStartfellows_DetailStaticControlCommand ?? new DelegateCommand(PinToStartfellows_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is fellowsSchema)) { return; }
                
                CurrentfellowsSchema = value as fellowsSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the fellows_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfofellows_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentfellowsSchema.Id.ToString(),
                Title = CurrentfellowsSchema.Subtitle,
                BackTitle = CurrentfellowsSchema.Subtitle,
                BackContent = CurrentfellowsSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentfellowsSchema.Image,
                BackBackgroundImagePath = CurrentfellowsSchema.Image,
                LogoPath = "Logo-fee674dd-17e3-4874-ad8f-9b2146854d85.png"
            };
            return tileInfo;
        }
    }
}
