// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of TheNextOne_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class TheNextOne_DetailViewModel : BindableBase, ITheNextOne_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="TheNextOne_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public TheNextOne_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private TheNextOneSchema _currentTheNextOneSchema;

        /// <summary>
        /// CurrentTheNextOneSchema property.
        /// </summary>		
        public TheNextOneSchema CurrentTheNextOneSchema
        {
            get
            {
				return _currentTheNextOneSchema;
            }
            set
            {
                SetProperty(ref _currentTheNextOneSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechTheNextOne_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentTheNextOneSchema.Subtitle + " " + CurrentTheNextOneSchema.Description);
        }
		

        private ICommand _textToSpeechTheNextOne_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechTheNextOne_DetailStaticControlCommand
        {
            get { return _textToSpeechTheNextOne_DetailStaticControlCommand = _textToSpeechTheNextOne_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechTheNextOne_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareTheNextOne_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentTheNextOneSchema.Subtitle, CurrentTheNextOneSchema.Description);
        }
		

        private ICommand _shareTheNextOne_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareTheNextOne_DetailStaticControlCommand
        {
            get { return _shareTheNextOne_DetailStaticControlCommand = _shareTheNextOne_DetailStaticControlCommand ?? new DelegateCommand(ShareTheNextOne_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartTheNextOne_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(ITheNextOne_DetailViewModel), CreateTileInfoTheNextOne_DetailStaticControl());
        }
		

        private ICommand _pinToStartTheNextOne_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartTheNextOne_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartTheNextOne_DetailStaticControlCommand
        {
            get { return _pinToStartTheNextOne_DetailStaticControlCommand = _pinToStartTheNextOne_DetailStaticControlCommand ?? new DelegateCommand(PinToStartTheNextOne_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is TheNextOneSchema)) { return; }
                
                CurrentTheNextOneSchema = value as TheNextOneSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the TheNextOne_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoTheNextOne_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentTheNextOneSchema.Subtitle,
                Title = CurrentTheNextOneSchema.Subtitle,
                BackTitle = CurrentTheNextOneSchema.Subtitle,
                BackContent = CurrentTheNextOneSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentTheNextOneSchema.Image,
                BackBackgroundImagePath = CurrentTheNextOneSchema.Image,
                LogoPath = "Logo-fee674dd-17e3-4874-ad8f-9b2146854d85.png"
            };
            return tileInfo;
        }
    }
}
