//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataAdmin
{


    public partial class GridViewPager
    {

        protected System.Web.UI.WebControls.ImageButton ImageButtonFirst;

        protected System.Web.UI.WebControls.ImageButton ImageButtonPrev;

        protected System.Web.UI.WebControls.Label LabelPage;

        protected System.Web.UI.WebControls.TextBox TextBoxPage;

        protected System.Web.UI.WebControls.Label LabelNumberOfPages;

        protected System.Web.UI.WebControls.ImageButton ImageButtonNext;

        protected System.Web.UI.WebControls.ImageButton ImageButtonLast;

        protected System.Web.UI.WebControls.Label LabelRows;

        protected System.Web.UI.WebControls.DropDownList DropDownListPageSize;
    }
}
