//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPAppStudio.Repositories.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPAppStudio.Repositories.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string DeserializeJSONError
        {
            get
            {
                return ResourceManager.GetString("DeserializeJSONError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string DataErrorFrom
        {
            get
            {
                return ResourceManager.GetString("DataErrorFrom", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string DataError
        {
            get
            {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string Rss1Error
        {
            get
            {
                return ResourceManager.GetString("Rss1Error", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string RssTitleError
        {
            get
            {
                return ResourceManager.GetString("RssTitleError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string RssLinkError
        {
            get
            {
                return ResourceManager.GetString("RssLinkError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string RssError
        {
            get
            {
                return ResourceManager.GetString("RssError", resourceCulture);
            }
        }
    }
}
