#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuidVsId
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="TestData")]
	public partial class DataClassesGuidDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGuidProduct(GuidProduct instance);
    partial void UpdateGuidProduct(GuidProduct instance);
    partial void DeleteGuidProduct(GuidProduct instance);
    partial void InsertGuidReleatedProduct(GuidReleatedProduct instance);
    partial void UpdateGuidReleatedProduct(GuidReleatedProduct instance);
    partial void DeleteGuidReleatedProduct(GuidReleatedProduct instance);
    #endregion
		
		public DataClassesGuidDataContext() : 
				base(global::GuidVsId.Properties.Settings.Default.TestDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGuidDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGuidDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGuidDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesGuidDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GuidProduct> GuidProducts
		{
			get
			{
				return this.GetTable<GuidProduct>();
			}
		}
		
		public System.Data.Linq.Table<GuidReleatedProduct> GuidReleatedProducts
		{
			get
			{
				return this.GetTable<GuidReleatedProduct>();
			}
		}
	}
	
	[Table(Name="dbo.guid_Products")]
	public partial class GuidProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Name;
		
		private float _Price;
		
		private EntitySet<GuidReleatedProduct> _guid_ReleatedProducts;
		
		private EntitySet<GuidReleatedProduct> _GuidReleatedProducts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(float value);
    partial void OnPriceChanged();
    #endregion
		
		public GuidProduct()
		{
			this._guid_ReleatedProducts = new EntitySet<GuidReleatedProduct>(new Action<GuidReleatedProduct>(this.attach_guid_ReleatedProducts), new Action<GuidReleatedProduct>(this.detach_guid_ReleatedProducts));
			this._GuidReleatedProducts = new EntitySet<GuidReleatedProduct>(new Action<GuidReleatedProduct>(this.attach_GuidReleatedProducts), new Action<GuidReleatedProduct>(this.detach_GuidReleatedProducts));
			OnCreated();
		}
		
		[Column(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Price", DbType="Real NOT NULL")]
		public float Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[Association(Name="GuidProduct_GuidReleatedProduct", Storage="_guid_ReleatedProducts", OtherKey="ProductIdFirst")]
		public EntitySet<GuidReleatedProduct> GuidReleatedProductsFirst
		{
			get
			{
				return this._guid_ReleatedProducts;
			}
			set
			{
				this._guid_ReleatedProducts.Assign(value);
			}
		}
		
		[Association(Name="GuidProduct_GuidReleatedProduct1", Storage="_GuidReleatedProducts", OtherKey="ProductIdSecond")]
		public EntitySet<GuidReleatedProduct> GuidReleatedProductsSecond
		{
			get
			{
				return this._GuidReleatedProducts;
			}
			set
			{
				this._GuidReleatedProducts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_guid_ReleatedProducts(GuidReleatedProduct entity)
		{
			this.SendPropertyChanging();
			entity.guid_Product = this;
		}
		
		private void detach_guid_ReleatedProducts(GuidReleatedProduct entity)
		{
			this.SendPropertyChanging();
			entity.guid_Product = null;
		}
		
		private void attach_GuidReleatedProducts(GuidReleatedProduct entity)
		{
			this.SendPropertyChanging();
			entity.GuidProduct = this;
		}
		
		private void detach_GuidReleatedProducts(GuidReleatedProduct entity)
		{
			this.SendPropertyChanging();
			entity.GuidProduct = null;
		}
	}
	
	[Table(Name="dbo.guid_ReleatedProducts")]
	public partial class GuidReleatedProduct : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _ProductIdFirst;
		
		private System.Guid _ProductIdSecond;
		
		private EntityRef<GuidProduct> _guid_Product;
		
		private EntityRef<GuidProduct> _GuidProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnProductIdFirstChanging(System.Guid value);
    partial void OnProductIdFirstChanged();
    partial void OnProductIdSecondChanging(System.Guid value);
    partial void OnProductIdSecondChanged();
    #endregion
		
		public GuidReleatedProduct()
		{
			this._guid_Product = default(EntityRef<GuidProduct>);
			this._GuidProduct = default(EntityRef<GuidProduct>);
			OnCreated();
		}
		
		[Column(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_ProductIdFirst", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductIdFirst
		{
			get
			{
				return this._ProductIdFirst;
			}
			set
			{
				if ((this._ProductIdFirst != value))
				{
					if (this._guid_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIdFirstChanging(value);
					this.SendPropertyChanging();
					this._ProductIdFirst = value;
					this.SendPropertyChanged("ProductIdFirst");
					this.OnProductIdFirstChanged();
				}
			}
		}
		
		[Column(Storage="_ProductIdSecond", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductIdSecond
		{
			get
			{
				return this._ProductIdSecond;
			}
			set
			{
				if ((this._ProductIdSecond != value))
				{
					if (this._GuidProduct.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductIdSecondChanging(value);
					this.SendPropertyChanging();
					this._ProductIdSecond = value;
					this.SendPropertyChanged("ProductIdSecond");
					this.OnProductIdSecondChanged();
				}
			}
		}
		
		[Association(Name="GuidProduct_GuidReleatedProduct", Storage="_guid_Product", ThisKey="ProductIdFirst", IsForeignKey=true)]
		public GuidProduct guid_Product
		{
			get
			{
				return this._guid_Product.Entity;
			}
			set
			{
				GuidProduct previousValue = this._guid_Product.Entity;
				if (((previousValue != value) 
							|| (this._guid_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._guid_Product.Entity = null;
						previousValue.GuidReleatedProductsFirst.Remove(this);
					}
					this._guid_Product.Entity = value;
					if ((value != null))
					{
						value.GuidReleatedProductsFirst.Add(this);
						this._ProductIdFirst = value.Id;
					}
					else
					{
						this._ProductIdFirst = default(System.Guid);
					}
					this.SendPropertyChanged("guid_Product");
				}
			}
		}
		
		[Association(Name="GuidProduct_GuidReleatedProduct1", Storage="_GuidProduct", ThisKey="ProductIdSecond", IsForeignKey=true)]
		public GuidProduct GuidProduct
		{
			get
			{
				return this._GuidProduct.Entity;
			}
			set
			{
				GuidProduct previousValue = this._GuidProduct.Entity;
				if (((previousValue != value) 
							|| (this._GuidProduct.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GuidProduct.Entity = null;
						previousValue.GuidReleatedProductsSecond.Remove(this);
					}
					this._GuidProduct.Entity = value;
					if ((value != null))
					{
						value.GuidReleatedProductsSecond.Add(this);
						this._ProductIdSecond = value.Id;
					}
					else
					{
						this._ProductIdSecond = default(System.Guid);
					}
					this.SendPropertyChanged("GuidProduct");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
