<?xml version="1.0" encoding="utf-8"?>
<Database Name="Database" EntityNamespace="SQLCompact" ContextNamespace="SQLCompact" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="CompanyEmployeeRelations" Member="Employees" OtherKey="CompanyId" Type="Employee" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="CompanyEmployeeRelations" Member="Company" ThisKey="CompanyId" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
</Database>