// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// diaryCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class diaryCollection : IdiaryCollection 
    {
        private readonly ObservableCollection<diarySchema> _data = new ObservableCollection<diarySchema>
		{
          new diarySchema
            {
                Id= new Guid("cf76d44d-b892-4132-ab0d-d6469c9074b5"),
                Title=@"06/06/2013",
                Subtitle=@"[Enter name for this day]",
                Image=@"..\Images\Item-5db64551-e2ca-4868-a6b0-3c095db10a2b.jpg",
                Description=@"[Insert the description of your day here]",
			},
          new diarySchema
            {
                Id= new Guid("cd38e0f3-8c89-4359-8f72-c060fbabba08"),
                Title=@"06/07/2013",
                Subtitle=@"[Enter name for this day]",
                Image=@"..\Images\Item-1e1243ba-6ae9-4754-b76f-20fed09a7804.jpg",
                Description=@"[Insert the description of your day here]",
			},
          new diarySchema
            {
                Id= new Guid("613af6fd-7b4e-483c-baf7-767a2c1a6eee"),
                Title=@"06/08/2013",
                Subtitle=@"[Enter name for this day]",
                Image=@"..\Images\Item-d64db236-a492-4b02-a05c-04af9a2ef2b3.jpg",
                Description=@"[Insert the description of your day here]",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of diarySchema items.
        /// </summary>
        /// <returns>An observable collection of diarySchema items.</returns>
        public ObservableCollection<diarySchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of diarySchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of diarySchema items.</returns>
        public ObservableCollection<diarySchema> Search(FilterSpecification filter)
        {
            return Filter<diarySchema>.FilterCollection(filter, _data);
        }
	}
}
