// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// fellowsCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class fellowsCollection : IfellowsCollection 
    {
        private readonly ObservableCollection<fellowsSchema> _data = new ObservableCollection<fellowsSchema>
		{
          new fellowsSchema
            {
                Id= new Guid("9dd2f674-4b5c-4fdc-af69-5be8381fe8e3"),
                Title=@"Frank",
                Subtitle=@"[Enter relationship]",
                Image=@"..\Images\Item-d4b645c0-9c5e-4297-b82c-b19baf9a0d59.jpg",
                Description=@"[Insert the description of your fellow traveler here]",
			},
          new fellowsSchema
            {
                Id= new Guid("e61faa36-e979-4ff4-81c4-6c4a6c7db5e8"),
                Title=@"James",
                Subtitle=@"[Enter relationship]",
                Image=@"..\Images\Item-799d1ffc-76ad-45f5-af18-4542df283171.png",
                Description=@"[Insert the description of your fellow traveler here]",
			},
          new fellowsSchema
            {
                Id= new Guid("b0114d03-cc80-43e6-9231-9d06f349edba"),
                Title=@"Sarah",
                Subtitle=@"[Enter relationship]",
                Image=@"..\Images\Item-53820e0f-ac05-4a5d-ab23-2191fd112584.jpg",
                Description=@"[Insert the description of your fellow traveler here]",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of fellowsSchema items.
        /// </summary>
        /// <returns>An observable collection of fellowsSchema items.</returns>
        public ObservableCollection<fellowsSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of fellowsSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of fellowsSchema items.</returns>
        public ObservableCollection<fellowsSchema> Search(FilterSpecification filter)
        {
            return Filter<fellowsSchema>.FilterCollection(filter, _data);
        }
	}
}
