// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// photosCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class photosCollection : IphotosCollection 
    {
        private readonly ObservableCollection<photosCollectionSchema> _data = new ObservableCollection<photosCollectionSchema>
		{
          new photosCollectionSchema
            {
                Id= new Guid("2c678cd9-4617-4699-bbd6-d9afb48e7181"),
                Title=@"Photo 01",
                Subtitle=@"Photo 01",
                Image=@"..\Images\Item-119d1d00-c72c-4107-8325-44561c9cc95a.jpg",
                Description=@"Photo 01",
			},
          new photosCollectionSchema
            {
                Id= new Guid("683ab039-2f9d-468f-ac51-a414d7369d39"),
                Title=@"Photo 02",
                Subtitle=@"Photo 02",
                Image=@"..\Images\Item-1b4db986-ff2a-4d7f-98bf-fb40dc1cd4d0.jpg",
                Description=@"Photo 02",
			},
          new photosCollectionSchema
            {
                Id= new Guid("966ef540-eecd-4e27-a810-a1e3db672d87"),
                Title=@"Photo 03",
                Subtitle=@"Photo 03",
                Image=@"..\Images\Item-1b08b4d4-184f-4ab3-bd60-db13fc237bdd.jpg",
                Description=@"Photo 03",
			},
          new photosCollectionSchema
            {
                Id= new Guid("423da8d6-fbbb-4d2a-b6e7-03572abaaedb"),
                Title=@"Photo 04",
                Subtitle=@"Photo 04",
                Image=@"..\Images\Item-c19eb103-d447-4397-a4f3-4ffeeb3dcac7.jpg",
                Description=@"Photo 04",
			},
          new photosCollectionSchema
            {
                Id= new Guid("96acf70c-c30a-4705-b0ea-f3948e3b98e6"),
                Title=@"Photo 05",
                Subtitle=@"Photo 05",
                Image=@"..\Images\Item-d5ab4269-6d70-4192-8e10-94e618496cd9.jpg",
                Description=@"Photo 05",
			},
          new photosCollectionSchema
            {
                Id= new Guid("2021803e-5742-45a8-8c77-e4bacb34a118"),
                Title=@"Photo 06",
                Subtitle=@"Photo 06",
                Image=@"..\Images\Item-7f186179-e373-4df3-aa44-d7c5fb4e453f.jpg",
                Description=@"Photo 06",
			},
          new photosCollectionSchema
            {
                Id= new Guid("e23a1ec3-c06b-4b9b-9481-96675ba2e959"),
                Title=@"Photo 07",
                Subtitle=@"Photo 07",
                Image=@"..\Images\Item-f7a41ce4-0e30-46dd-8c6a-36ad592e642c.jpg",
                Description=@"Photo 07",
			},
          new photosCollectionSchema
            {
                Id= new Guid("d40e000c-692c-400f-bdda-465bea838c96"),
                Title=@"Photo 08",
                Subtitle=@"Photo 08",
                Image=@"..\Images\Item-fed90989-b2cd-4c37-9cae-3377c128e4c1.jpg",
                Description=@"Photo 08",
			},
          new photosCollectionSchema
            {
                Id= new Guid("901cbb04-adfa-48a6-9b2e-e4b03e13cbbe"),
                Title=@"Photo 09",
                Subtitle=@"Photo 09",
                Image=@"..\Images\Item-d1fbd823-69ab-4459-a12b-de9347b21d7c.jpg",
                Description=@"Photo 09",
			},
          new photosCollectionSchema
            {
                Id= new Guid("78ab9264-4bf0-46f3-b4b8-0ebf0010297e"),
                Title=@"Photo 10",
                Subtitle=@"Photo 10",
                Image=@"..\Images\Item-a2ed732b-a509-4237-a45d-f4d6922dbf14.jpg",
                Description=@"Photo 10",
			},
          new photosCollectionSchema
            {
                Id= new Guid("12539b61-13eb-46d3-a6a9-5c6d0b0e731b"),
                Title=@"Photo 11",
                Subtitle=@"Photo 11",
                Image=@"..\Images\Item-9a53cbf7-f293-4bac-afb9-943709c3dc29.jpg",
                Description=@"Photo 11",
			},
          new photosCollectionSchema
            {
                Id= new Guid("7a7f86d6-5447-4173-b69f-0dfcc0514c09"),
                Title=@"Photo 12",
                Subtitle=@"Photo 12",
                Image=@"..\Images\Item-f13d9eba-bedb-47d9-81e0-d029a1464ea9.jpg",
                Description=@"Photo 12",
			},
          new photosCollectionSchema
            {
                Id= new Guid("dc74f6a5-65cb-4ba6-a571-a8aa0b6effd6"),
                Title=@"Photo 13",
                Subtitle=@"Photo 13",
                Image=@"..\Images\Item-c51e6e1d-91fe-4bf6-99fc-2630ab5434f7.jpg",
                Description=@"Photo 13",
			},
          new photosCollectionSchema
            {
                Id= new Guid("79d34251-300b-49f9-81d5-68df8c7c2a4d"),
                Title=@"Photo 14",
                Subtitle=@"Photo 14",
                Image=@"..\Images\Item-813d3c99-a5c5-49c7-b983-d0d592ef8e76.jpg",
                Description=@"Photo 14",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of photosCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of photosCollectionSchema items.</returns>
        public ObservableCollection<photosCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of photosCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of photosCollectionSchema items.</returns>
        public ObservableCollection<photosCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<photosCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
