// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using WPAppStudio.Ioc;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Container();
        }

        /// <summary>
        /// Gets the reference to a ThePlace_InfoViewModel.
        /// </summary>
		public IThePlace_InfoViewModel ThePlace_InfoViewModel
        {
            get { return _container.Resolve<ThePlace_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a TheNextOne_DetailViewModel.
        /// </summary>
		public ITheNextOne_DetailViewModel TheNextOne_DetailViewModel
        {
            get { return _container.Resolve<TheNextOne_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a fellows_DetailViewModel.
        /// </summary>
		public Ifellows_DetailViewModel fellows_DetailViewModel
        {
            get { return _container.Resolve<fellows_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a diary_DetailViewModel.
        /// </summary>
		public Idiary_DetailViewModel diary_DetailViewModel
        {
            get { return _container.Resolve<diary_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a photos_DetailViewModel.
        /// </summary>
		public Iphotos_DetailViewModel photos_DetailViewModel
        {
            get { return _container.Resolve<photos_DetailViewModel>(); }
        }
    }
}
