//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataAdmin
{


    public partial class Site
    {

        protected System.Web.UI.HtmlControls.HtmlForm form1;

        protected System.Web.UI.ScriptManager ScriptManager1;

        protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}
