//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.312
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavascriptAndXml {
    
    
    /// <summary>
    /// _Default-Klasse.
    /// </summary>
    /// <remarks>
    /// Automatisch generierte Klasse.
    /// </remarks>
    public partial class _Default {
        
        /// <summary>
        /// form1-Steuerelement.
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Verschieben Sie zum Ändern die Felddeklaration aus der Designerdatei in die Code-Behind-Datei.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1-Steuerelement.
        /// </summary>
        /// <remarks>
        /// Automatisch generiertes Feld.
        /// Verschieben Sie zum Ändern die Felddeklaration aus der Designerdatei in die Code-Behind-Datei.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
    }
}
