//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataAdmin
{


    public partial class List
    {

        protected System.Web.UI.WebControls.Content Content1;

        protected System.Web.DynamicData.DynamicDataManager DynamicDataManager1;

        protected System.Web.UI.ScriptManagerProxy ScriptManagerProxy1;

        protected System.Web.UI.UpdatePanel UpdatePanel1;

        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;

        protected System.Web.DynamicData.DynamicValidator GridViewValidator;

        protected System.Web.DynamicData.FilterRepeater FilterRepeater;

        protected System.Web.DynamicData.FilterUserControlBase DynamicFilter;

        protected System.Web.UI.WebControls.GridView GridView1;

        protected System.Web.UI.WebControls.HyperLink EditHyperLink;

        protected System.Web.UI.WebControls.LinkButton DeleteLinkButton;

        protected System.Web.UI.WebControls.HyperLink DetailsHyperLink;

        protected System.Web.UI.WebControls.EntityDataSource GridDataSource;

        protected System.Web.UI.WebControls.HyperLink InsertHyperLink;
    }
}
