//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPAppStudio.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPAppStudio.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
				        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
				        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string HomeUrl {
            get {
                return ResourceManager.GetString("HomeUrl", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string TryAgain
        {
            get
            {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string PinError
        {
            get
            {
                return ResourceManager.GetString("PinError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string SpeechError
        {
            get
            {
                return ResourceManager.GetString("SpeechError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string StorageError
        {
            get
            {
                return ResourceManager.GetString("StorageError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string TileError
        {
            get
            {
                return ResourceManager.GetString("TileError", resourceCulture);
            }
        }
		
		/// <summary>
        ///   
        /// </summary>
        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string for BackgroundImagePngUrl.
        /// </summary>
        public static string BackgroundImagePngUrl {
            get {
                return ResourceManager.GetString("BackgroundImagePngUrl", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for AppLogoPngUrl.
        /// </summary>
        public static string AppLogoPngUrl {
            get {
                return ResourceManager.GetString("AppLogoPngUrl", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for DynamicDataError.
        /// </summary>
        public static string DynamicDataError {
            get {
                return ResourceManager.GetString("DynamicDataError", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for SetLockScreen.
        /// </summary>
        public static string SetLockScreen {
            get {
                return ResourceManager.GetString("SetLockScreen", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for TextToSpeech.
        /// </summary>
        public static string TextToSpeech {
            get {
                return ResourceManager.GetString("TextToSpeech", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }

        
        /// <summary>
        ///   Looks up a localized string for PinToStart.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }

    }
}
