// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// fellows_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Ifellows_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentfellowsSchema property.
        /// </summary>
		fellowsSchema CurrentfellowsSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechfellows_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechfellows_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharefellows_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharefellows_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartfellows_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartfellows_DetailStaticControlCommand { get; }

	}
}
