// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// photos_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Iphotos_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentphotosCollectionSchema property.
        /// </summary>
		photosCollectionSchema CurrentphotosCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechphotos_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechphotos_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharephotos_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharephotos_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartphotos_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartphotos_DetailStaticControlCommand { get; }

	}
}
