// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// TheNextOne_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ITheNextOne_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentTheNextOneSchema property.
        /// </summary>
		TheNextOneSchema CurrentTheNextOneSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechTheNextOne_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechTheNextOne_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareTheNextOne_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareTheNextOne_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartTheNextOne_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartTheNextOne_DetailStaticControlCommand { get; }

	}
}
