//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDataAdmin
{


    public partial class Decimal_EditField
    {

        protected System.Web.UI.WebControls.TextBox TextBox1;

        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        protected System.Web.UI.WebControls.CompareValidator CompareValidator1;

        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;

        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;

        protected System.Web.DynamicData.DynamicValidator DynamicValidator1;
    }
}
