// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   UnityContainer.tt
using Microsoft.Practices.Unity;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.Repositories;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Container : IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<ILiveTileService, LiveTileService>();
			_currentContainer.RegisterType<ILockScreenService, LockScreenService>();
            _currentContainer.RegisterType<IDialogService, DialogService>();
            _currentContainer.RegisterType<IReminderService, ReminderService>();
            _currentContainer.RegisterType<IShareService, ShareService>();
            _currentContainer.RegisterType<ISpeechService, SpeechService>();
            _currentContainer.RegisterType<INavigationService, NavigationService>();
			_currentContainer.RegisterType<IJsonDataSource, JsonDataSource>();
			_currentContainer.RegisterType<IXmlDataSource, XmlDataSource>();
			_currentContainer.RegisterType<IYoutubeDataSource, YoutubeDataSource>();
			
            _currentContainer.RegisterType<IThePlace_InfoViewModel, ThePlace_InfoViewModel>();
            _currentContainer.RegisterType<ITheNextOne_DetailViewModel, TheNextOne_DetailViewModel>();
            _currentContainer.RegisterType<Ifellows_DetailViewModel, fellows_DetailViewModel>();
            _currentContainer.RegisterType<Idiary_DetailViewModel, diary_DetailViewModel>();
            _currentContainer.RegisterType<Iphotos_DetailViewModel, photos_DetailViewModel>();
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<IThePlaceDataSource, ThePlaceDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IphotosCollection, photosCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IdiaryCollection, diaryCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IfellowsCollection, fellowsCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<ITheNextOneCollection, TheNextOneCollection>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<IThePlaceDataSource, FakeThePlaceDataSource>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IphotosCollection, FakephotosCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IdiaryCollection, FakediaryCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<IfellowsCollection, FakefellowsCollection>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<ITheNextOneCollection, FakeTheNextOneCollection>(new ContainerControlledLifetimeManager());
			
			}	
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
